#!/usr/bin/env ruby

require 'fileutils'
require_relative 'loader'

@parser = Parser.new

@parser.parse ""
@parser.parse "\n"
@parser.parse "alias"
@parser.parse "alias\n"
@parser.parse "alias;"
@parser.parse "A = 1 + 2"
