#!/usr/bin/env ruby

require 'fileutils'
require_relative 'loader'

@parser = Parser.new


@parser.parse ""
@parser.parse "\n"
@parser.parse "alias"
@parser.parse "alias;"
@parser.parse "alias\n"
@parser.parse "alias\n;"
@parser.parse "ls;"
@parser.parse "alias lsd = 'ls -a';"
@parser.parse "A"
@parser.parse "A = 1 + 2"
@parser.parse "A = 3 + 4 + 5 + 6;"
