#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module ToothBrush
  class Parser < Racc::Parser


attr_accessor :result

  def lex(code)
    @lexer = Lexer.new(code)
    @lexer.tokenize #Kickstart lexer
  end

  def parse(code)
    lex(code)
    @result
    do_parse
  end

  def next_token
    @lexer.next_token 
  end
##### State transition tables begin ###

racc_action_table = [
     8,     8,     9,     9,    25,    14,     5,     4,     7,     7,
    19,    13,    13,     8,    18,     9,     5,    16,    19,    19,
     5,     7,    18,    18,    13,   -15,    22,    26,   nil,   -15 ]

racc_action_check = [
     0,    13,     0,    13,    19,     1,     0,     0,     0,    13,
    21,     0,    13,    18,    21,    18,     6,     6,     6,    24,
    16,    18,     6,    24,    18,    20,    14,    25,   nil,    20 ]

racc_action_pointer = [
    -2,     5,   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,
   nil,   nil,   nil,    -1,    26,   nil,    12,   nil,    11,   -11,
    15,     0,   nil,   nil,     9,    17,   nil ]

racc_action_default = [
    -1,   -21,    -2,    -3,    -4,    -5,    -6,   -10,   -11,   -12,
   -13,   -14,   -15,   -16,   -21,    -7,    -8,   -18,   -21,   -21,
   -17,   -21,    27,    -9,   -19,   -21,   -20 ]

racc_goto_table = [
     6,     2,     3,     1,    20,   nil,   nil,    15,   nil,   nil,
   nil,   nil,   nil,    21,   nil,   nil,   nil,    23,    24 ]

racc_goto_check = [
     4,     2,     3,     1,     7,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,     4,   nil,   nil,   nil,     2,     4 ]

racc_goto_pointer = [
   nil,     3,     1,     2,     0,   nil,   nil,    -9,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    11,    10,    12,    17 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 20, :_reduce_none,
  1, 20, :_reduce_2,
  1, 20, :_reduce_3,
  1, 20, :_reduce_4,
  1, 21, :_reduce_none,
  1, 22, :_reduce_6,
  2, 22, :_reduce_7,
  2, 22, :_reduce_8,
  3, 22, :_reduce_9,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 25, :_reduce_none,
  2, 25, :_reduce_none,
  2, 26, :_reduce_none,
  3, 26, :_reduce_19,
  3, 27, :_reduce_none ]

racc_reduce_n = 21

racc_shift_n = 27

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENTIFIER => 2,
  :PARAMETERS => 3,
  :STRING => 4,
  :WHITESPACE => 5,
  :INDENT => 6,
  :toke => 7,
  :TERMINATOR => 8,
  :NEWLINE => 9,
  :NUMBER => 10,
  :OPERATOR => 11,
  :FUNCTION => 12,
  :ALIAS => 13,
  :ASSIGNMENT => 14,
  :ADDITION => 15,
  :SUBSTRACTION => 16,
  :MULTIPLICATION => 17,
  :DIVISION => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENTIFIER",
  "PARAMETERS",
  "STRING",
  "WHITESPACE",
  "INDENT",
  "toke",
  "TERMINATOR",
  "NEWLINE",
  "NUMBER",
  "OPERATOR",
  "FUNCTION",
  "ALIAS",
  "ASSIGNMENT",
  "ADDITION",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "$start",
  "Root",
  "Terminator",
  "Command",
  "Expression",
  "Literal",
  "Alias",
  "Assignment",
  "Addition" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

def _reduce_2(val, _values, result)
 parse_error! "Unexpected Token Found '#{val[0]}'" 
    result
end

def _reduce_3(val, _values, result)
 paint "Reached Command : #{val[0]}\n" , :cyan 
    result
end

def _reduce_4(val, _values, result)
 paint "Reached NEWLINE : #{val[0]}\n" , :magenta 
    result
end

# reduce 5 omitted

def _reduce_6(val, _values, result)
 paint "Reached Expression : #{val[0]}\n" , :yellow 
    result
end

def _reduce_7(val, _values, result)
 paint "Reached Expression Terminator : #{val[0]}\n" , :white 
    result
end

def _reduce_8(val, _values, result)
 paint "Expression NEWLINE : #{val[0]} | #{val[1].inspect}\n" , :white 
    result
end

def _reduce_9(val, _values, result)
 paint "Expression NEWLINE Terminator : #{val[0]} | #{val[1].inspect} | #{val[2]}\n" , :red 
    result
end

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

def _reduce_19(val, _values, result)
 paint "Assignment #{val[0]} | #{val[1]} | #{val[2]}\n" 
    result
end

# reduce 20 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module ToothBrush
